version: '3.3'
services:

  trino_a:
    image: trinodb/trino
    container_name: trino_a
    ports:
      - 8080:8080
    volumes:
      - ./trino_a.config.properties:/etc/trino/config.properties
      - ./jvm.config:/etc/trino/jvm.config

  trino_b:
    image: trinodb/trino
    container_name: trino_b
    ports:
      - 8081:8081
    volumes:
      - ./trino_b.config.properties:/etc/trino/config.properties
      - ./jvm.config:/etc/trino/jvm.config

  trino_worker:
    image: trinodb/trino
    container_name: trino_worker
    volumes:
      - ./trino_worker.config.properties:/etc/trino/config.properties
      - ./jvm.config:/etc/trino/jvm.config

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
